# Agent Instructions

## Documentation lookup

When writing or reviewing code that uses any external library or framework
(FastAPI, SQLAlchemy, Pydantic, React, React Router, Vite, Tailwind, Vitest,
Playwright, vite-plugin-pwa, Workbox, or any other third-party package), fetch
up-to-date documentation with Context7 before generating code or answering API
questions. Do not rely on training-data knowledge alone for library APIs.

## Frontend architecture contract

The frontend is a React Router SSR application. Keep SSR enabled and preserve
`react-router-serve` as the production runtime unless the deployment model is
explicitly redesigned.

Do not read `import.meta.env` directly outside `frontend/app/shared/config/env.ts`
and `frontend/app/shared/config/runtime.ts`. Public frontend settings must flow
through those helpers.

Prefer explicit type-safe checks over implicit truthy/falsy conditions. Use
guards from `frontend/app/shared/lib/type-guards.ts` (`isNil`, `isNull`,
`isUndefined`, `isNonNil`, `isNumber`, `isString`, `isNonEmptyString`,
`isBoolean`, `isRecord`, `isArrayOf`) or explicit comparisons. Project-wide
type utilities belong in `frontend/app/shared/types/types.ts`: reusable helpers
under `Utils`, domain-neutral global types under `GlobalTypes`.

Required production frontend env vars:

- `VITE_API_BASE_URL`
- `VITE_PUBLIC_SITE_URL`
- `VITE_PUBLIC_APP_NAME` when the default `Template App` name is not desired

`VITE_PUBLIC_SITE_URL` is the canonical public origin. It is used for canonical
URLs, `robots.txt`, and `sitemap.xml`; production builds must not guess it.

## SEO contract

Every React Router route must make an explicit SEO decision through
`buildRouteMeta` from `frontend/app/shared/lib/seo.ts`.

Use these profiles:

- `publicIndexable`: public pages that should appear in search results.
- `publicNoIndex`: public utility pages that should not be indexed.
- `privateNoIndex`: authenticated, account, dashboard, admin, or user-specific
  pages.

Rules:

- Private/authenticated routes must use `privateNoIndex`.
- `/login`, `/register`, and `/dashboard` must remain `noindex,nofollow`.
- New indexable public routes must be added to both public route allowlists:
  `frontend/app/shared/lib/seo.ts` and `frontend/scripts/site-config.mjs`.
- Do not generate the sitemap from all routes automatically; the sitemap is an
  allowlist by design.
- Each public indexable page needs a unique title and description.
- Keep canonical URLs absolute and based on `VITE_PUBLIC_SITE_URL`.

## Sitemap and robots

`robots.txt` and `sitemap.xml` are generated by:

```bash
cd frontend
pnpm generate:sitemap
```

The generated files live in `frontend/public` for development/static copying and
are also synced into `build/client` when a build already exists.

After adding, removing, or changing public indexable routes, run:

```bash
cd frontend
pnpm generate:sitemap
pnpm check:seo
```

## PWA contract

The template uses a conservative PWA setup through `vite-plugin-pwa`.

PWA intent:

- provide installability;
- generate `manifest.webmanifest`;
- register a service worker only in production;
- precache static build assets and app icons;
- avoid offline-first behavior for auth, API, and private application routes.

Rules:

- Do not cache `/api/*` responses in the service worker.
- Do not precache auth/private route chunks unless a dedicated offline security
  design is added first.
- Do not add offline mutation queues or background sync to the template by
  default.
- If adding more private route chunks, update the PWA `globIgnores` in
  `frontend/vite.config.ts` and extend `frontend/scripts/check-pwa.mjs`.
- If replacing the app icon, update all PWA/favicons together:
  `favicon.svg`, `pwa-icon.svg`, and `pwa-maskable-icon.svg`.

## i18n and SEO

The current template keeps the existing language switcher/localStorage/browser
detection model. It updates `<html lang>`, but it does not implement SEO URL
locales.

If the product needs multilingual SEO, redesign this as a separate phase with
locale URLs such as `/en/...` and `/ru/...`, plus canonical/hreflang support.
Do not add `hreflang` while the language is not represented in the URL.

## Production infra contract

Nginx owns production edge headers. Keep these behaviors unless replacing nginx
with another edge layer:

- HTTPS redirect and HSTS.
- Immutable cache headers for `/assets/*`.
- No aggressive HTML caching.
- `Referrer-Policy`.
- `Permissions-Policy`.
- CSP starts as `Content-Security-Policy-Report-Only`.

Do not change CSP from report-only to blocking without testing third-party
scripts, analytics, error tracking, payment widgets, fonts, images, and React
Router hydration.

## Required checks

Before handing off frontend changes that affect routing, SEO, PWA, SSR, env, or
infra, run:

```bash
cd frontend
pnpm lint
pnpm typecheck
pnpm test
VITE_API_BASE_URL=http://localhost:8000 \
VITE_PUBLIC_SITE_URL=http://localhost:3000 \
VITE_PUBLIC_APP_NAME="Template App" \
pnpm build:ci
pnpm test:e2e:lint
```

For SSR/e2e checks, start the built app and run Playwright against it:

```bash
cd frontend
VITE_API_BASE_URL=http://localhost:8000 \
VITE_PUBLIC_SITE_URL=http://localhost:3000 \
VITE_PUBLIC_APP_NAME="Template App" \
pnpm start

PLAYWRIGHT_BASE_URL=http://localhost:3000 pnpm test:e2e:chromium
```

For nginx syntax, use local nginx or Docker with temporary certificates if the
production certificate path does not exist.
