/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Live */
        get: operations["health_live_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/detailed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Detailed */
        get: operations["health_detailed_api_v1_health_detailed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Backup */
        get: operations["health_backup_api_v1_health_backup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_public_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_public_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_public_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_public_auth_me_get"];
        put?: never;
        post?: never;
        /** Delete Me */
        delete: operations["delete_me_api_v1_public_auth_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/progress/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Progress */
        post: operations["sync_progress_api_v1_public_progress_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/progress/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Progress Me */
        get: operations["get_progress_me_api_v1_public_progress_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_public_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Public Tasks */
        get: operations["list_public_tasks_api_v1_public_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/tasks/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Public Task */
        get: operations["get_public_task_api_v1_public_tasks__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/practice/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Public Practice */
        get: operations["get_public_practice_api_v1_public_practice__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Public Practice Answer */
        post: operations["validate_public_practice_answer_api_v1_public_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Feedback */
        post: operations["submit_feedback_api_v1_public_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Feedback */
        get: operations["list_feedback_api_v1_admin_feedback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/feedback/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Feedback Status */
        patch: operations["update_feedback_status_api_v1_admin_feedback__report_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** FeedbackRequest */
        FeedbackRequest: {
            /** Page Url */
            page_url: string;
            /** Message */
            message: string;
            /** Honeypot */
            honeypot?: string;
        };
        /** FeedbackResponse */
        FeedbackResponse: {
            /** Ok */
            ok: boolean;
        };
        /** FeedbackStatus */
        FeedbackStatus: "new" | "reviewed" | "archived";
        /** FeedbackReportAdmin */
        FeedbackReportAdmin: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Page Url */
            page_url: string;
            /** Message */
            message: string;
            /** Ip Hash */
            ip_hash: string;
            /** User Agent */
            user_agent: string | null;
            status: components["schemas"]["FeedbackStatus"];
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
        };
        /** FeedbackStatusUpdate */
        FeedbackStatusUpdate: {
            status: components["schemas"]["FeedbackStatus"];
        };
        /** FeedbackListResponse */
        FeedbackListResponse: {
            /** Items */
            items: components["schemas"]["FeedbackReportAdmin"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
        };
        /** AssetManifestItem */
        AssetManifestItem: {
            /** Url */
            url: string;
            /** Alt */
            alt: string;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
            /** Original Path */
            original_path: string;
            /** Optimized Path */
            optimized_path?: string | null;
        };
        /** CodeBlock */
        CodeBlock: {
            /** Language */
            language: string;
            /** Title */
            title?: string | null;
            /** Code */
            code: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** PracticeValidationRequest */
        PracticeValidationRequest: {
            /**
             * Itemid
             * Format: uuid
             */
            itemId: string;
            /** Answer */
            answer: string;
        };
        /** PracticeValidationResponse */
        PracticeValidationResponse: {
            /** Correct */
            correct: boolean;
            /** Expectedvalue */
            expectedValue?: string | null;
            /** Explanationhtml */
            explanationHtml?: string | null;
        };
        /** PublicPracticeItem */
        PublicPracticeItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Taskid
             * Format: uuid
             */
            taskId: string;
            /** Taskslug */
            taskSlug: string;
            /** Tasktitle */
            taskTitle: string;
            /** Egenumber */
            egeNumber: number;
            /** Position */
            position: number;
            /** Year */
            year: number | null;
            /** Prompthtml */
            promptHtml: string;
            codeBlock: components["schemas"]["CodeBlock"] | null;
        };
        /** PublicPracticePreview */
        PublicPracticePreview: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Taskid
             * Format: uuid
             */
            taskId: string;
            /** Position */
            position: number;
            /** Year */
            year: number | null;
        };
        /** PublicTaskDetail */
        PublicTaskDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Egenumber */
            egeNumber: number;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string | null;
            difficulty: components["schemas"]["TaskDifficulty"];
            /** Estimatedminutes */
            estimatedMinutes: number | null;
            /** Practicecount */
            practiceCount: number;
            /** Publishedat */
            publishedAt: string | null;
            /** Theoryhtml */
            theoryHtml: string;
            /** Theorytoc */
            theoryToc: components["schemas"]["TheoryTocItem"][];
            /** Assetmanifest */
            assetManifest: components["schemas"]["AssetManifestItem"][];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Practice */
            practice: components["schemas"]["PublicPracticePreview"][];
        };
        /** PublicTaskSummary */
        PublicTaskSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Egenumber */
            egeNumber: number;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string | null;
            difficulty: components["schemas"]["TaskDifficulty"];
            /** Estimatedminutes */
            estimatedMinutes: number | null;
            /** Practicecount */
            practiceCount: number;
            /** Publishedat */
            publishedAt: string | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Consent 152Fz
             * @constant
             */
            consent_152fz: true;
        };
        /**
         * TaskDifficulty
         * @enum {string}
         */
        TaskDifficulty: "basic" | "medium" | "high";
        /** TheoryTocItem */
        TheoryTocItem: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Depth */
            depth: number;
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            role: components["schemas"]["UserRole"];
            /** Is Active */
            is_active: boolean;
            /** Consent 152Fz */
            consent_152fz: boolean;
            /** Consent At */
            consent_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "user" | "admin";
        /** SyncAttemptItem */
        SyncAttemptItem: {
            /** Practiceitemiid */
            practiceItemId: string;
            /** Iscorrect */
            isCorrect: boolean;
            /** Attemptscount */
            attemptsCount: number;
            /**
             * Lastansweredat
             * Format: date-time
             */
            lastAnsweredAt: string;
        };
        /** ProgressSyncRequest */
        ProgressSyncRequest: {
            /** Attempts */
            attempts: components["schemas"]["SyncAttemptItem"][];
        };
        /** ProgressSyncResponse */
        ProgressSyncResponse: {
            /** Synced */
            synced: number;
            /** Updated */
            updated: number;
        };
        /** ProfileStats */
        ProfileStats: {
            /** Totaltasks */
            totalTasks: number;
            /** Solvedtasks */
            solvedTasks: number;
            /** Correctattempts */
            correctAttempts: number;
            /** Totalattempts */
            totalAttempts: number;
            /** Streak */
            streak: number;
            /** Lastactivityat */
            lastActivityAt: string | null;
        };
        /** WeakTask */
        WeakTask: {
            /** Taskid */
            taskId: string;
            /** Taskslug */
            taskSlug: string;
            /** Tasktitle */
            taskTitle: string;
            /** Egenumber */
            egeNumber: number;
            /** Solvedcount */
            solvedCount: number;
            /** Totalcount */
            totalCount: number;
            /** Accuracy */
            accuracy: number;
        };
        /** RecentActivity */
        RecentActivity: {
            /** Date */
            date: string;
            /** Count */
            count: number;
        };
        /** ProfileMe */
        ProfileMe: {
            stats: components["schemas"]["ProfileStats"];
            /** Weaktasks */
            weakTasks: components["schemas"]["WeakTask"][];
            /** Recentactivity */
            recentActivity: components["schemas"]["RecentActivity"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_live_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_detailed_api_v1_health_detailed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_backup_api_v1_health_backup_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    login_api_v1_public_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_public_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_public_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_public_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    logout_api_v1_public_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_public_tasks_api_v1_public_tasks_get: {
        parameters: {
            query?: {
                search?: string | null;
                difficulty?: components["schemas"]["TaskDifficulty"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicTaskSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_public_task_api_v1_public_tasks__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicTaskDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_public_practice_api_v1_public_practice__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicPracticeItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_public_practice_answer_api_v1_public_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PracticeValidationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeValidationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_me_api_v1_public_auth_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sync_progress_api_v1_public_progress_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgressSyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressSyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_progress_me_api_v1_public_progress_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileMe"];
                };
            };
        };
    };
    submit_feedback_api_v1_public_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_feedback_api_v1_admin_feedback_get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                status?: components["schemas"]["FeedbackStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_feedback_status_api_v1_admin_feedback__report_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackReportAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
